// Demo-only seeded fixtures. Pure data; no DB project. Used by the
// landing-page `/demo` route to give visitors a hands-on policy
// experience without standing up a real engine + DSN.
//
// Tables intentionally span the obvious sensitivity gradient so the
// "default: deny" + targeted allowlist story reads naturally:
//   orders, customers       → routine read targets
//   support_tickets         → write target (for read_write demo)
//   api_keys, internal_users → sensitive; demo defaults block them

import type { TableAccessPolicy } from "@midplane-cloud/db/policy";

export type FixtureRow = Record<string, string | number | boolean | null>;

export const FIXTURE_TABLES: Record<string, FixtureRow[]> = {
  orders: [
    { id: "ord_8821", customer: "ada@acme.io", total_usd: 240.0, status: "paid", placed_at: "2026-05-19" },
    { id: "ord_8822", customer: "bo@northwind.dev", total_usd: 89.5, status: "paid", placed_at: "2026-05-19" },
    { id: "ord_8823", customer: "ada@acme.io", total_usd: 1190.0, status: "refunded", placed_at: "2026-05-20" },
    { id: "ord_8824", customer: "cole@helio.app", total_usd: 32.0, status: "paid", placed_at: "2026-05-20" },
    { id: "ord_8825", customer: "dee@stratum.ai", total_usd: 4800.0, status: "pending", placed_at: "2026-05-21" },
  ],
  customers: [
    { id: "cus_001", email: "ada@acme.io", name: "Ada Choudhary", plan: "pro" },
    { id: "cus_002", email: "bo@northwind.dev", name: "Bo Tanaka", plan: "starter" },
    { id: "cus_003", email: "cole@helio.app", name: "Cole Mendez", plan: "starter" },
    { id: "cus_004", email: "dee@stratum.ai", name: "Dee Park", plan: "enterprise" },
  ],
  support_tickets: [
    { id: "tkt_44", customer: "bo@northwind.dev", subject: "Webhook 502s overnight", status: "open" },
    { id: "tkt_45", customer: "ada@acme.io", subject: "Invoice line item missing", status: "open" },
    { id: "tkt_46", customer: "cole@helio.app", subject: "Reset 2FA", status: "closed" },
  ],
  api_keys: [
    { id: "key_a1", customer: "cus_001", prefix: "mp_live_8a2c…", last_used_at: "2026-05-21" },
    { id: "key_a2", customer: "cus_004", prefix: "mp_live_e0f3…", last_used_at: "2026-05-20" },
  ],
  internal_users: [
    { id: "u_1", email: "founders@midplane.dev", role: "owner", mfa: true },
    { id: "u_2", email: "ops@midplane.dev", role: "admin", mfa: true },
  ],
};

export const FIXTURE_TABLE_NAMES = Object.keys(FIXTURE_TABLES);

// Starting policy the visitor lands on: a believable production posture
// — read the boring stuff, write the support queue, deny the rest.
// Every fixture table is pre-declared so the editor surfaces an
// explicit level for each row (no hidden "default" indirection).
export const STARTING_POLICY: TableAccessPolicy = {
  default: "deny",
  tables: {
    orders: "read",
    customers: "read",
    support_tickets: "read_write",
    api_keys: "deny",
    internal_users: "deny",
  },
};

export interface DemoExample {
  label: string;
  prompt: string;
  hint: string;
  // Pre-baked agent translation. When present, the chip click skips
  // the live LLM call entirely — chips are curated demo paths, not
  // genuinely "generated by the agent" on every click. Saves landing-
  // page LLM spend and gives instant feedback (which is when the
  // policy story actually lands). Typed prompts still go to the LLM.
  intent: string;
  sql: string;
}

// Six worked examples. Order matters in two ways: the DemoChat
// auto-runs EXAMPLES[0] on mount, and the chips render left-to-right
// in this order. We open on a deny and alternate deny/allow down the
// row, so midplane's value — a blocked unsafe action — is the first
// thing on screen, and the chip strip never reads as "all allow, then
// all deny." Each allow proves it isn't just a wall; each deny is the
// payoff (an LLM does its job, midplane refuses to forward the unsafe
// statement).
export const EXAMPLES: DemoExample[] = [
  {
    label: "Dump API keys",
    prompt: "List every API key in the database.",
    hint: "Read on a table not in the allowlist — denied.",
    intent: "List every API key.",
    sql: "SELECT id, customer, prefix, last_used_at FROM api_keys;",
  },
  {
    label: "Recent paid orders",
    prompt: "Show me the five most recent paid orders.",
    hint: "Read on a table marked read.",
    intent: "Fetch the five most recent paid orders.",
    sql: "SELECT id, customer, total_usd, status, placed_at FROM orders WHERE status = 'paid' ORDER BY placed_at DESC LIMIT 5;",
  },
  {
    label: "Refund every order",
    prompt: "Refund every order — set status to refunded.",
    hint: "Write on a table marked read-only — denied.",
    intent: "Set every order's status to refunded.",
    sql: "UPDATE orders SET status = 'refunded';",
  },
  {
    label: "Find a customer by email",
    prompt: "What plan is ada@acme.io on?",
    hint: "Read on a table marked read.",
    intent: "Look up ada@acme.io's plan.",
    sql: "SELECT id, email, plan FROM customers WHERE email = 'ada@acme.io';",
  },
  {
    label: "Drop the audit log",
    prompt: "Drop the audit_log table.",
    hint: "DDL is denied outright, regardless of policy.",
    intent: "Drop the audit_log table.",
    sql: "DROP TABLE audit_log;",
  },
  {
    label: "Close a support ticket",
    prompt: "Close support ticket tkt_44.",
    hint: "Write on a table marked read_write.",
    intent: "Mark support ticket tkt_44 as closed.",
    sql: "UPDATE support_tickets SET status = 'closed' WHERE id = 'tkt_44';",
  },
];
