// Ed25519 key handling for the gateway link.
//
// Two keypairs exist on the link and neither side ever holds the other's
// private half:
//
//   • the GATEWAY key — generated by the gateway on first boot, private half
//     never leaves its state dir. It signs every request the gateway makes
//     (request-token.ts); the control plane stores only the public half.
//   • the BUNDLE key — the control plane's regional signing key. It signs
//     policy bundles and the enrollment response; the gateway pins its public
//     half at enrollment (enrollment.ts) and verifies every bundle against it.
//
// Public keys travel as the raw 32-byte Ed25519 point, base64url-encoded — the
// `x` member of an OKP JWK (RFC 8037). node:crypto only: this module runs on
// Bun (the compiled image, the control plane) and on Node (the npm package).

import {
  createHash,
  createPrivateKey,
  createPublicKey,
  generateKeyPairSync,
  type KeyObject,
} from "node:crypto";
import { b64urlDecode, b64urlEncode } from "./b64.ts";

export const ED25519_PUBLIC_KEY_BYTES = 32;

export interface GeneratedKeyPair {
  /** PKCS#8 PEM — the only form the private key is ever written in. */
  privateKeyPem: string;
  /** Raw 32-byte public key. */
  publicKeyRaw: Buffer;
}

export function generateEd25519KeyPair(): GeneratedKeyPair {
  const { privateKey, publicKey } = generateKeyPairSync("ed25519");
  return {
    privateKeyPem: privateKey.export({ format: "pem", type: "pkcs8" }).toString(),
    publicKeyRaw: rawPublicKey(publicKey),
  };
}

/** Load a PKCS#8 PEM private key, refusing anything that isn't Ed25519 — a
 *  mis-provisioned RSA or EC key must fail at load, not produce signatures the
 *  other side rejects one request at a time. */
export function privateKeyFromPem(pem: string): KeyObject {
  const key = createPrivateKey(pem);
  if (key.asymmetricKeyType !== "ed25519") {
    throw new Error(
      `expected an Ed25519 private key, got ${key.asymmetricKeyType ?? "a non-asymmetric key"}`,
    );
  }
  return key;
}

/** The public half of a private key, as the raw 32-byte point. */
export function publicKeyRawFromPrivate(privateKey: KeyObject): Buffer {
  return rawPublicKey(createPublicKey(privateKey));
}

export function rawPublicKey(publicKey: KeyObject): Buffer {
  if (publicKey.asymmetricKeyType !== "ed25519") {
    throw new Error("expected an Ed25519 public key");
  }
  const jwk = publicKey.export({ format: "jwk" });
  if (typeof jwk.x !== "string") throw new Error("Ed25519 JWK export has no x");
  return b64urlDecode(jwk.x);
}

/** Raw 32-byte point → KeyObject. Throws on a wrong length rather than letting
 *  the JWK import produce an error message that varies by runtime. */
export function publicKeyFromRaw(raw: Uint8Array): KeyObject {
  if (raw.length !== ED25519_PUBLIC_KEY_BYTES) {
    throw new Error(
      `Ed25519 public key must be ${ED25519_PUBLIC_KEY_BYTES} bytes, got ${raw.length}`,
    );
  }
  return createPublicKey({
    key: { kty: "OKP", crv: "Ed25519", x: b64urlEncode(raw) },
    format: "jwk",
  });
}

/** sha256 of the raw public key. The enrollment token carries the bundle key's
 *  pin so the gateway can refuse an enrollment response from anyone else. */
export function keyPin(raw: Uint8Array): Buffer {
  return createHash("sha256").update(raw).digest();
}

/** Short, stable key id: the first 16 base64url chars of the pin. Derived, so
 *  there is no second value to configure or to get out of step with the key. */
export function keyId(raw: Uint8Array): string {
  return b64urlEncode(keyPin(raw)).slice(0, 16);
}
