// Live end-to-end: seed → /mcp/<token> handshake → SELECT 1 → audit row.
//
// Gated on E2E_LIVE=1 so CI / `bun run test:e2e` smoke runs don't try to spin
// up Docker. Requires:
//   - docker on PATH (sidecar Postgres + OSS image spawn)
//   - midplane/midplane:0.10.0 image present (`bun run dev:image`)
//   - .env.local DATABASE_URL pointing at a Neon dev branch (writes a row,
//     cleaned up in afterAll)
//   - .env.local MIDPLANE_KMS_DEV_KEY_EU set (already auto-generated by
//     bootstrap.sh — the encryptDsn path uses it)
//
// Why this test exists: the unit suite proves each piece in isolation
// (DecryptCache, DsnResolver, ContainerRegistry, DockerSpawner). This is the
// only thing that proves they compose correctly into the actual user-visible
// trust posture: paste a DSN, get an MCP endpoint, an agent talks to it,
// and an audit row lands in the OSS container's SQLite.
//
// Signup is NOT exercised here — this suite seeds the cloud DB directly and
// drives the proxy/container pipeline. The signup → first MCP request path is
// covered end-to-end by signup.live.e2e.ts. The
// programmatic createConnection path uses the same encryption code that
// the Server Action behind the paste-DSN form uses, so the cryptographic
// trust posture is identical to what a real signup would produce.

import { execSync } from "node:child_process";

import { expect, test } from "@playwright/test";
import { eq } from "drizzle-orm";

import { connections, customers, getDb } from "@midplane-cloud/db";

import { containerNameFor, seedConnection } from "./_seed-helpers";

test.skip(
  process.env.E2E_LIVE !== "1",
  "set E2E_LIVE=1 to run live proxy E2E (requires Docker + Neon)",
);

const PG_NAME = `midplane-e2e-pg-${Date.now()}`;
const PG_PASSWORD = "postgres";
const PG_DB = "midplane_e2e";

let pgPort = 0;
let mcpToken = "";
let customerId = "";
let connectionId = "";
let proxiedContainerName = "";

test.beforeAll(async () => {
  // 1. Sidecar Postgres reachable from the spawned OSS container.
  // We bind to a random host port; the container reaches it via the host
  // network bridge (host.docker.internal on macOS).
  execSync(
    `docker run -d --rm --name ${PG_NAME} -e POSTGRES_PASSWORD=${PG_PASSWORD} -e POSTGRES_DB=${PG_DB} -p 0:5432 postgres:16-alpine`,
    { stdio: ["ignore", "pipe", "pipe"] },
  );
  const portOut = execSync(`docker port ${PG_NAME} 5432`).toString();
  const m = /:(\d+)$/m.exec(portOut.split(/\r?\n/)[0] ?? "");
  if (!m?.[1]) throw new Error(`could not parse pg port: ${portOut}`);
  pgPort = Number(m[1]);

  await waitForPgDb();
  execSync(
    `docker exec ${PG_NAME} psql -U postgres -d ${PG_DB} -c "CREATE TABLE t (n int); INSERT INTO t VALUES (1);"`,
    { stdio: ["ignore", "pipe", "pipe"] },
  );

  // 2. Cloud DB seed: customer + encrypted connection + connection_databases
  // + mcp_tokens row pointing at the sidecar Postgres. seedConnection
  // mints a real token (HMAC-hashed via the regional pepper) so the
  // proxy's resolveByToken finds it the same way a UI-created connection
  // would. The container reaches the sidecar via host.docker.internal.
  const customerDsn = `postgres://postgres:${PG_PASSWORD}@host.docker.internal:${pgPort}/${PG_DB}`;
  const seeded = await seedConnection({ region: "eu", dsn: customerDsn });
  customerId = seeded.customerId;
  connectionId = seeded.connectionId;
  mcpToken = seeded.tokenPlaintext;
  proxiedContainerName = containerNameFor(connectionId);
});

test.afterAll(async () => {
  // Best-effort cleanup; failures here shouldn't mask a test pass.
  try {
    execSync(`docker rm -f ${PG_NAME}`, { stdio: "ignore" });
  } catch {}
  if (proxiedContainerName) {
    try {
      execSync(`docker rm -f ${proxiedContainerName}`, { stdio: "ignore" });
    } catch {}
  }
  if (connectionId || customerId) {
    const db = getDb("eu");
    if (connectionId) {
      await db.delete(connections).where(eq(connections.id, connectionId));
    }
    if (customerId) {
      await db.delete(customers).where(eq(customers.id, customerId));
    }
  }
});

test("proxy handshake + SELECT 1 + audit row lands in container SQLite", async ({
  request,
  baseURL,
}) => {
  // Streamable HTTP initialize.
  const initRes = await request.post(`${baseURL}/mcp/${mcpToken}`, {
    headers: {
      "content-type": "application/json",
      accept: "application/json, text/event-stream",
    },
    data: {
      jsonrpc: "2.0",
      id: 1,
      method: "initialize",
      params: {
        protocolVersion: "2024-11-05",
        capabilities: {},
        clientInfo: { name: "midplane-e2e", version: "0.0.0" },
      },
    },
  });
  expect(initRes.status(), await initRes.text()).toBe(200);
  const sessionId = initRes.headers()["mcp-session-id"];
  expect(sessionId, "OSS transport must mint mcp-session-id").toBeTruthy();

  // initialized notification — required to complete the handshake.
  const ackRes = await request.post(`${baseURL}/mcp/${mcpToken}`, {
    headers: {
      "content-type": "application/json",
      accept: "application/json, text/event-stream",
      "mcp-session-id": sessionId!,
    },
    data: {
      jsonrpc: "2.0",
      method: "notifications/initialized",
    },
  });
  expect(ackRes.status()).toBeLessThan(300);

  // tools/call query "SELECT 1" — happy path through parser + policy + exec.
  const callRes = await request.post(`${baseURL}/mcp/${mcpToken}`, {
    headers: {
      "content-type": "application/json",
      accept: "application/json, text/event-stream",
      "mcp-session-id": sessionId!,
    },
    data: {
      jsonrpc: "2.0",
      id: 2,
      method: "tools/call",
      params: { name: "query", arguments: { sql: "SELECT n FROM t" } },
    },
  });
  expect(callRes.status(), await callRes.text()).toBe(200);
  const callBody = await readJsonRpc(callRes);
  expect(JSON.stringify(callBody)).toContain("1"); // SELECT n returned 1

  // Audit log inside the spawned container — the OSS engine writes
  // ATTEMPTED + DECIDED + EXECUTED rows on a successful query.
  const auditCount = execSync(
    `docker exec ${proxiedContainerName} sqlite3 /data/audit.db 'SELECT COUNT(*) FROM audit_events'`,
  )
    .toString()
    .trim();
  expect(Number(auditCount)).toBeGreaterThanOrEqual(3);
});

async function readJsonRpc(res: import("@playwright/test").APIResponse) {
  const ct = res.headers()["content-type"] ?? "";
  if (ct.includes("text/event-stream")) {
    const text = await res.text();
    // Pick the last JSON payload from the SSE stream.
    const lines = text.split(/\r?\n/).filter((l) => l.startsWith("data:"));
    const last = lines[lines.length - 1] ?? "";
    return JSON.parse(last.slice(5).trim());
  }
  return res.json();
}

async function waitForPgDb(deadlineMs = 30_000): Promise<void> {
  // pg_isready reports ready before initdb finishes creating POSTGRES_DB,
  // so we probe the actual database with a SELECT 1 instead.
  const deadline = Date.now() + deadlineMs;
  while (Date.now() < deadline) {
    try {
      execSync(
        `docker exec ${PG_NAME} psql -U postgres -d ${PG_DB} -c 'SELECT 1' -t`,
        { stdio: ["ignore", "pipe", "pipe"] },
      );
      return;
    } catch {
      await new Promise((r) => setTimeout(r, 200));
    }
  }
  throw new Error(`sidecar Postgres database not ready within ${deadlineMs}ms`);
}
