#!/usr/bin/env bun
// Builds the publishable `midplane` npm package into dist/.
//
//   bun engine/packages/mcp-server/scripts/build-npm.ts
//
// The npm artifact is a Node artifact: `npx midplane` runs under whatever node
// the user has, not under Bun. So this bundles for --target=node and inlines
// the workspace-internal @midplane/engine (which is never published), while
// leaving the eight real runtime dependencies external so they install and
// audit normally — a vendored copy of pg inside our tarball would hide it from
// `npm audit` and from Dependabot.
//
// Not minified on purpose. This is a security tool; someone evaluating what
// `npx midplane` actually does should be able to read the published artifact.
//
// The Docker image does NOT use this script — it compiles src/cli.ts straight
// to a self-contained binary (engine/docker/Dockerfile). Two build paths, one
// source tree.

import { chmodSync, existsSync, rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const PKG_DIR = dirname(dirname(fileURLToPath(import.meta.url)));
const DIST = join(PKG_DIR, "dist");
const ENTRY = join(PKG_DIR, "src", "cli.ts");
// dist/cli.js is a version guard that defers to dist/main.js — see below.
const OUT = join(DIST, "main.js");
const BIN = join(DIST, "cli.js");

// Minimum Node. Below this, node:sqlite does not exist and the audit log cannot
// open. Keep in sync with package.json engines.node.
const MIN_NODE = { major: 22, minor: 16 };

const pkg = (await Bun.file(join(PKG_DIR, "package.json")).json()) as {
  name: string;
  version: string;
  bin: Record<string, string>;
  dependencies: Record<string, string>;
};

// Everything in `dependencies` stays external; everything else (i.e.
// @midplane/engine, a devDependency) gets inlined. Deriving the list from the
// manifest means a new dependency can't be silently bundled — or silently
// omitted from what the consumer installs.
const external = Object.keys(pkg.dependencies).flatMap((d) => [d, `${d}/*`]);

rmSync(DIST, { recursive: true, force: true });

const result = await Bun.build({
  entrypoints: [ENTRY],
  outdir: DIST,
  // The bundle is dist/main.js; dist/cli.js is the version guard written below.
  naming: "[dir]/main.[ext]",
  target: "node",
  format: "esm",
  external,
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  throw new Error("bundle failed");
}

let code = await Bun.file(OUT).text();

// The source shebang is `#!/usr/bin/env bun` — correct for `./src/cli.ts` in a
// checkout, wrong for the thing npm links onto a user's PATH.
const NODE_SHEBANG = "#!/usr/bin/env node";
code = code.startsWith("#!")
  ? NODE_SHEBANG + code.slice(code.indexOf("\n"))
  : `${NODE_SHEBANG}\n${code}`;

await Bun.write(OUT, code);

// The bin is a version guard, not the bundle, because on an unsupported Node
// the bundle cannot even be parsed. `engines` does not stop an install (npm
// only warns unless engine-strict is set), so an old-Node user reaches the
// code — and what they get is a SyntaxError from whichever dependency happens
// to use a newer builtin first. Measured on Node 18: "The requested module
// 'node:util' does not provide an export named 'styleText'", which names none
// of the packages involved and gives no hint that the fix is a Node upgrade.
//
// This has to be a SEPARATE file. ESM hoists every static import above the
// module body, so a check at the top of the bundle — or prepended as a banner —
// runs only after the imports that crash have already been evaluated. A dynamic
// import is the one form that defers loading, and .then() is used over top-level
// await so this file itself parses on any Node old enough to have `import()`.
await Bun.write(
  BIN,
  `${NODE_SHEBANG}
// Generated by scripts/build-npm.ts — do not edit.
const [major, minor] = process.versions.node.split(".").map(Number);
if (major < ${MIN_NODE.major} || (major === ${MIN_NODE.major} && minor < ${MIN_NODE.minor})) {
  process.stderr.write(
    "midplane requires Node ${MIN_NODE.major}.${MIN_NODE.minor}+ (or 24+), which is where the node:sqlite\\n" +
      "builtin it uses for the audit log became available. This is " + process.version + ".\\n" +
      "Upgrade Node, or run the Docker image instead: https://midplane.ai/docs\\n",
  );
  process.exit(1);
}
import("./main.js").catch((err) => {
  process.stderr.write(String(err?.stack ?? err) + "\\n");
  process.exit(1);
});
`,
);

chmodSync(OUT, 0o755);
chmodSync(BIN, 0o755);

// ── Post-conditions ─────────────────────────────────────────────────────────
//
// These are the failure modes that would ship a package that installs fine and
// then dies on first run, which is the worst way to fail — so assert them here
// rather than discovering them from a user's bug report.

const problems: string[] = [];

// A `bun:` specifier reaching Node is ERR_UNSUPPORTED_ESM_URL_SCHEME at import
// time. The sqlite driver resolves its builtin through a computed specifier
// precisely so this can't happen; this catches a future literal import.
for (const m of code.matchAll(/(?:from\s*|import\s*\(\s*)["'](bun:[^"']+)["']/g)) {
  problems.push(`bundle imports the Bun builtin "${m[1]}" — Node cannot load it`);
}

const binCode = await Bun.file(BIN).text();
if (!binCode.startsWith(NODE_SHEBANG)) problems.push("bin is missing the node shebang");

// The guard is worthless if it ever stops being the first thing to run, which
// is what a stray static import in this file would cause.
if (/^\s*import\s+[^(]/m.test(binCode)) {
  problems.push("bin has a STATIC import — it would be hoisted above the version guard");
}
if (!binCode.includes(`${MIN_NODE.major}`) || !binCode.includes(`${MIN_NODE.minor}`)) {
  problems.push("bin does not carry the minimum Node version");
}

// The version is inlined from package.json at build time (`midplane version`,
// the MCP server's advertised version, the telemetry `version` field). A stale
// bundle would report the wrong one.
if (!code.includes(pkg.version)) {
  problems.push(`bundle does not carry version ${pkg.version}`);
}

const binTarget = join(PKG_DIR, pkg.bin.midplane!);
if (!existsSync(binTarget)) problems.push(`bin target missing: ${pkg.bin.midplane}`);

for (const f of ["README.md", "LICENSE"]) {
  if (!existsSync(join(PKG_DIR, f))) {
    problems.push(`${f} is missing — it is listed in "files" and npm would omit it`);
  }
}

// npm runs a content classifier over published tarballs, and it reads literal
// destructive SQL as an attack payload rather than as documentation. The 0.19.0
// release was blocked by exactly this: a README illustrating what the engine
// BLOCKS ("DELETE FROM users", "SELECT 1; DROP TABLE users") was refused with a
// bare 403 whose body the npm CLI never surfaces — it took a publish-bisect to
// find. Being a security tool is what makes us prone to it.
//
// So this README describes the guarantees instead of demonstrating them, and
// points at the docs and the repo README for worked examples. Those two are NOT
// published to npm and keep their concrete SQL.
//
// Checked at build time rather than in CI alone, because the failure mode is a
// release that dies at the npm step with the image already published.
const readme = await Bun.file(join(PKG_DIR, "README.md")).text();
const FLAGGED = [
  /\bDELETE\s+FROM\s+\w/i,
  /\bDROP\s+TABLE\s+\w/i,
  /\bTRUNCATE\s+TABLE?\s+\w/i,
  /;\s*DROP\b/i,
];
for (const re of FLAGGED) {
  const m = readme.match(re);
  if (m) {
    problems.push(
      `README.md contains literal destructive SQL (${JSON.stringify(m[0])}), which npm's ` +
        `content classifier rejects with a 403 at publish time. Describe the behavior ` +
        `instead, and link to the docs for the worked example.`,
    );
  }
}

if (problems.length > 0) {
  for (const p of problems) console.error(`[build-npm] ${p}`);
  process.exit(1);
}

const bytes = Buffer.byteLength(code);
console.log(
  `[build-npm] ${pkg.name}@${pkg.version} → dist/cli.js (${(bytes / 1024).toFixed(0)} KB, ${external.length / 2} external deps)`,
);
